# Generated by Django 5.0.1 on 2024-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_skills', models.JSONField(default=list)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=50)),
                ('area_name', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
